name: issuesOpenAutoAdd
on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "새로운이슈"
  auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
          - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: jl917
                  numOfAssignee: 1
                  allowSelfAssign: true
